codewarm/dsnalgo/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'dsnalgo'

urlpatterns = [
	#/dsnalgo/
    url(r'^$', views.dsnalgo, name='index'),

    #/dsnalgo/1/
    url(r'^(?P<article_id>[0-9]+)/$', views.article_detail, name='article-detail'),

    #/dsnalgo/1/2/
    url(r'^(?P<article_id>[0-9]+)/(?P<sub_article_id>[0-9]+)/$', views.sub_article_detail, name='sub_article-detail'),
]

codewarm/summer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^dsnalgo/', include('dsnalgo.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codewarm/dsnalgo/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=250)

    def __str__(self):
        return self.title

class SubArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)

    def __str__(self):
        return self.title

class PythonCode(models.Model):
    sub_article = models.ForeignKey(SubArticle, on_delete=models.CASCADE)
    code = models.TextField(max_length=5000)

    def __str__(self):
        return self.sub_article.title

class JavaCode(models.Model):
    sub_article = models.ForeignKey(SubArticle, on_delete=models.CASCADE)
    code = models.TextField(max_length=5000)

    def __str__(self):
        return self.sub_article.title

class CCode(models.Model):
    sub_article = models.ForeignKey(SubArticle, on_delete=models.CASCADE)
    code = models.TextField(max_length=5000)

    def __str__(self):
        return self.sub_article.title

codewarm/dsnalgo/views.py
from django.shortcuts import render, get_object_or_404
from . models import Article, SubArticle

def dsnalgo(request):
    all_articles = Article.objects.all()
    context = {'all_articles':all_articles}
    return render(request, 'dsnalgo/article_list.html', context)

def article_detail(request,article_id):
    #article = Article.object.get(pk=article_id)
    article = get_object_or_404(Article, pk=article_id)
    all_articles = Article.objects.all()
    context = {'article':article, 'all_articles':all_articles}
    return render(request, 'dsnalgo/article_detail.html', context)

def sub_article_detail(request, article_id, sub_article_id):
    sub_article = get_object_or_404(SubArticle,pk=sub_article_id)
    article = get_object_or_404(Article, pk=article_id)
    all_articles = Article.objects.all()
    context = {'article': article, 'all_articles': all_articles, 'sub_article':sub_article}
    return render(request,'dsnalgo/sub_article_detail.html',context)

codewarm/dsnalgo/templates/dsnalgo/article_detail.html
{% extends 'dsnalgo/base.html' %}

{% block title %}<title>{{ article.title }}</title> {% endblock %}
{% block article %}

    <div class="article">
        <ul class="sb_menu">
            <h2>{{ article.title }}</h2>
            {% for sub in article.subarticle_set.all %}
                <li><a href="{% url 'sub_article-detail' article.id sub.id %}">{{ sub.title }}</a></li>
            {% endfor %}
        </ul>

    </div>

{% endblock %}

codewarm/dsnalgo/templates/dsnalgo/article_list.html
{% extends 'dsnalgo/base.html' %}

{% block title %}<title>Data Structure & Algorithms</title> {% endblock %}

{% block article %}

    <div class="article">
        <ul class="sb_menu">
          {% for article in all_articles %}
            <a href="{% url 'article-detail' article.id %}"><h2>{{ article.title }}</h2></a>

            {% for sub in article.subarticle_set.all %}
                <li><a href="{% url 'sub_article-detail' article.id sub.id %}">{{ sub.title }}</a></li>
            {% endfor %}
          {% endfor %}
        </ul>
    </div>

{% endblock %}

codewarm/dsnalgo/templates/dsnalgo/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
{% block title %}<title>Home</title> {% endblock %}
  {% load staticfiles %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="{% static 'dsnalgo/style.css' %}" rel="stylesheet" type="text/css" />
  <link href="http://alexgorbatchev.com/pub/sh/current/styles/shThemeMidnight.css" rel="stylesheet" type="text/css" />
  <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shCore.js" type="text/javascript"></script>
  <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushJScript.js" type="text/javascript"></script>
  <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushPython.js" type="text/javascript"></script>
  <link href="http://alexgorbatchev.com/pub/sh/current/styles/shCore.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript">
    SyntaxHighlighter.all()
  </script>

</head>
<body>

<div class="main">

  <div class="header">
    <div class="header_resize">
      <div class="logo"><h1><a href="{% url 'index' %}">Code Warm</a></h1></div>
      <div class="menu_nav">
        <ul>
          <li><a href="{% url 'index' %}"><span>Home</span></a></li>
          <li><a href="{% url 'index' %}"><span>Ds&Algo</span></a></li>
        </ul>
      </div>
      <div class="clr"></div>
    </div>
  </div>

  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
        <div class="submb">
        {% block article %}

        {% endblock %}
        </div>
      </div>
      <div class="sidebar">
        <div class="gadget">
          <ul class="sb_menu">
            {% block quick_links %}
            {% endblock %}
            <h2 class="star">Topics</h2>
            {% for article in all_articles %}
              <li><a href="{% url 'article-detail' article.id %}">{{ article.title }}</a></li>
            {% endfor %}

          </ul>
        </div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
</div>
{% block body %}
{% endblock %}

</body>
</html>

codewarm/dsnalgo/templates/dsnalgo/sub_article_detail.html
{% extends 'dsnalgo/base.html' %}

{% block title %}<title>{{ sub_article.title }}</title> {% endblock %}

{% block article %}

    <div class="article">
        <ul class="sb_menu">
            <h2>{{ sub_article.title }}</h2>
            {% for code in sub_article.pythoncode_set.all %}
                <pre class="brush:py">
                    {{ code.code }}
                </pre>
            {% endfor %}
        </ul>

    </div>

{% endblock %}

{% block quick_links %}
    <ul class="sb_menu">
        <h2 class="star">{{ article.title }}</h2>
        {% for sub in article.subarticle_set.all %}
            <li><a href="{% url 'sub_article-detail' article.id sub.id %}">{{ sub.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}